"""add composite unique constraint and invite_token

Revision ID: b8ddc8c1cdbe
Revises: 88e19050a4e7
Create Date: 2026-04-16 10:56:39.100247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ddc8c1cdbe'
down_revision: Union[str, Sequence[str], None] = '88e19050a4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
