"""remove unique constraint on oauth_id

Revision ID: 88e19050a4e7
Revises: d230fdf7b8fb
Create Date: 2026-04-16 10:35:09.050781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e19050a4e7'
down_revision: Union[str, Sequence[str], None] = 'd230fdf7b8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_oauth_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_oauth_id_key'), 'users', ['oauth_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
