"""add invite_token to organizations

Revision ID: d230fdf7b8fb
Revises: f3f2b5a2f38b
Create Date: 2026-04-16 09:27:55.478185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd230fdf7b8fb'
down_revision: Union[str, Sequence[str], None] = 'f3f2b5a2f38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('invite_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['invite_token'])
    op.add_column('users', sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('unique_email_per_organization'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('unique_email_per_organization'), 'users', ['email', 'organization_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'invite_token')
    # ### end Alembic commands ###
